config/routes.rb
Rails.application.routes.draw do

  get 'bookings/new'

  root 'flights#index'
  get 'bookings' => 'bookings#new'
  post 'bookings' => 'bookings#create'

  resources :bookings, only: [:show]

end

app/models/airport.rb
class Airport < ActiveRecord::Base

  has_many :departing_flights, class_name: "Flight",
                                              foreign_key: "departing_airport_id"
  has_many :arriving_flights, class_name: "Flight",
                                           foreign_key: "arrival_airport_id"
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :flight
  has_many :passengers, dependent: :destroy

  accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ActiveRecord::Base
  belongs_to :departing_airport, class_name: "Airport"
  belongs_to :arrival_airport, class_name: "Airport"
  has_many :bookings, dependent: :destroy
  has_many :passengers, through: :bookings
end

app/models/passenger.rb
class Passenger < ActiveRecord::Base
  belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @flight = Flight.find(params[:flight_id])
    @booking = @flight.bookings.build
    params[:passengers].to_i.times {@booking.passengers.build}
  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      PassengerMailer.confirmation_email(@booking).deliver_later
      redirect_to @booking
    else
      render :new
    end
  end

  def show
    booking = Booking.find(params[:id])
    @flight = booking.flight
    @passengers = booking.passengers
  end

  private

  def booking_params
    params.require(:booking).permit(:flight_id,
        passengers_attributes: [:first_name, :last_name, :email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @airport_options = Airport.all.map {|a| [a.name, a.id]}
    @date_options = Flight.all.map {|f| f.date}.uniq
    @flights = Flight.where(departing_airport: params[:departing_airport_id],
                                          arrival_airport: params[:arrival_airport_id],
                                          date: params[:date]) unless params.nil?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<h1 class="center">Book flight</h1>



<%= form_for @booking do |f| %>
<%= f.hidden_field :flight_id %>
<% count = 1 %>
<%= f.fields_for :passengers do |ff| %>
<div class="form-inline center">
  <div class="form-group">
    <%= ff.label "#{count.ordinalize} passenger:" %>
    <%= ff.text_field :first_name, placeholder: "First name" %>
    <%= ff.text_field :last_name, placeholder: "Last name" %>
    <%= ff.text_field :email, placeholder: "Email" %>
  </div>
  <% count += 1 %>
  <% end %>
</div>
<%= f.submit "Book", class:"btn btn-primary" %>
<% end %>

app/views/bookings/show.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <h2 class="success">You have successfully booked your flight!</h2>

    <fieldset>
      <legend>Details</legend>
      <h3>
        Flight No. <%= @flight.id %> from <%= @flight.departing_airport.name %>(<%= @flight.departing_airport.code %>) to <%= @flight.arrival_airport.name %>(<%= @flight.arrival_airport.code %>)
      </h3>
      <p>
        <strong>Flying on <%= @flight.date.strftime("%d %B %Y") %></strong>
      </p>
      <p>
        <strong>Passengers:</strong>
      </p>
      <% @passengers.each do |p| %>
      <p>
        <%= p.first_name %> <%= p.last_name %>
      </p>
      <% end %>
    </fieldset>
  </div>
</div>

app/views/flights/index.html.erb
<h1 class="center">Find Flights</h1>

<div class="form-inline center">
    <%= form_tag(root_url, method: "get") do %>

    <%= select_tag(:departing_airport_id, options_for_select(@airport_options),
    include_blank: "From", class: "form-control") %>
    <%= select_tag(:arrival_airport_id, options_for_select(@airport_options),
    include_blank: "To", class: "form-control") %>
    <%= select_tag(:date, options_for_select(@date_options),
    include_blank: "Date", class: "form-control") %>
    <%= select_tag(:passengers, options_for_select(1..4),
    include_blank: "Passengers", class: "form-control") %>
    <%= submit_tag "Search", class:"btn btn-default" %>
    <% end %>
</div>





<% if @flights.any? %>

<h1 class="select-flight">Select Flight</h1>

<table class="table">
  <thead>
    <tr>
      <th>Select</th>
      <th>Flight</th>
      <th>Date</th>
      <th>From</th>
      <th>To</th>
      <th>Duration</th>
    </tr>
  </thead>
  <tbody>
  <%= form_for(:booking, url: bookings_path, method: "get") do |f| %>
    <% @flights.each do |flight| %>
    <td><%= radio_button_tag :flight_id, flight.id %></td>
    <td><%= flight.id %></td>
    <td><%= flight.date.strftime("%d %m %Y") %></td>
    <td><%= flight.departing_airport.name %></td>
    <td><%= flight.arrival_airport.name %></td>
    <td><%= flight.duration %></td>
    <td><%= hidden_field_tag :passengers, params[:passengers] %></td>
    <td><%= f.submit "Select flight", class: "btn btn-primary" %></td>
    <% end %>
  <% end %>
  </tbody>
</table>


<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FlightBooker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">

    <%= yield %>

  </div>

</body>
</html>